_BASE_: "../../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "checkpoints/voc/retinanet/retinanet_R_101_FPN_base1/model_0039999.pth" #"detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RETINANET:
    NUM_CLASSES: 15
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_base1', 'voc_2012_trainval_base1')
  TEST: ('voc_2007_test_base1',)
# SOLVER:
#   STEPS: (12000, 16000)
#   MAX_ITER: 18000  # 17.4 epochs
#   WARMUP_ITERS: 100
OUTPUT_DIR: "checkpoints/voc/retinanet/retinanet_R_101_FPN_base1_plus"
